spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybookstore
    username: root
    password: 19990926
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration: #指定mybatis全局配置文件中的相关项
    map-underscore-to-camel-case: true